### PR TITLE
Issue/17

### LINKED ISSUE #17: PHP 8 deprecation notice - usort() returning bool
### Expected behavior

I expect to not get any deprecation notices.

### Actual behavior

I'm getting the following notice:

```
PHP Deprecated:  usort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in edd-email-reports/includes/functions.php on line 329
```

### Steps to reproduce the behavior
1) Use PHP 8.
2) Not sure where I got the error -- maybe while previewing the report email?

### Information (if a specific version is affected):
PHP Version: 8

Email Reports Version (or branch):

EDD Version (or branch):

WordPress Version:

Any other relevant information:

### PR DESCRIPTION
**Pull request by rwebster85**
Fixes #17 deprecated notice in PHP 8

Proposed Changes:
1. Changed callback function `edd_email_reports_sort_best_selling_downloads()` used for `usort()` to return an integer, as per function spec. Equality returns 0, less than returns -1, greater than returns 1.

### CODE REVIEW

File: includes/functions.php [hunk 1]
```diff
@@ -359,10 +359,13 @@ function edd_email_reports_weekly_best_selling_downloads() {
...
  *
- * @return [type]    [description]
+ * @return int   Returns either -1, 0, or 1, depending on the comparison of $a and $b.
  */
 function edd_email_reports_sort_best_selling_downloads( $a, $b ) {
-	return $a['earnings'] < $b['earnings'];
+	if ( $a['earnings'] == $b['earnings'] ) {
+		return 0;
+	}
+	return ( $a['earnings'] < $b['earnings'] ) ? -1 : 1;
```
Comment (ashleyfae) [inline includes/functions.php:368]: For our particular use case, I think we want to reverse this. If a is less than b, then return `1`. As it is now, it's showing the lower earnings first:

Screenshot from 2021-07-06 11-27-43

But if I reverse it, the $10 ones show up first:

Screenshot from 2021-07-06 11-29-18

**Review by ashleyfae — CHANGES_REQUESTED** [review]

File: includes/functions.php (hunk 1 above)
Comment (rwebster85) [reply includes/functions.php]: Sorted that one :)

**Review by ashleyfae — APPROVED** [review]
Nice job :raised_hands:
